server:
    port: 8080

datasource:
  username: myuser
  password: mypassword
  host: jdbc:mysql://localhost:3306/mydb
  driver: mysql
  database: mydb
  port: 3306
  zone: America%2FEL_Salvador

auth:
  secure:
    hash_cost: 14
  register:
    errors:
      USER_ALREADY_EXISTS:
        code: "409"
        message: "El usuario ya existe"
      INVALID_EMAIL:
        code: "400"
        message: "El correo no es v√°lido"
      INTERNAL:
        code: "500"
        message: "Error interno del servidor"
    success:
      message: ""
      code: "200"
  registration:
    default:
      status: "active"